---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jgonzalezguevara/proxmox-rke2-platform.git
    targetRevision: main
    path: argocd/apps/argocd-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
